export enum ApiPaths {
    GetAllAuctionsByUser = '/auctions/all-by-user',
    CreateAuction = '/auctions/all',
    GetAllAuctions = '/auctions/all',
    GetAuction = '/auctions',
    CancelAuctionWithBidCheck = '/auctions/cancelWithBidCheck',
    CancelAuction = '/auctions/cancel',
    UpdateAuction = '/auctions',
    MakeBid = '/bids',
    GetAllBidsByUser = '/bids/all-by-user',
    GetBidCount = '/bids/bid-count',
    GetUploadUrl = '/upload-url',
    AddItem = '/items/add',
    GetItem = '/items',
    GetAllCategories = '/categories/all',
    GetAllUserItemsOnAuction = '/items/on-auction',
    GetAllUserItems = '/items/all-by-user',
    DeleteItem = '/items',
    DeleteItemOnAuction = '/items/on-auction',
    Login = '/register',
    SaveProfile = '/profile',
    GetProfile = '/profile',
    CheckUsernameAvailability = '/profile/username',
    DeleteAccount = '/account/user'
}